### ISSUE TITLE
浏览过营销号后在本网页打开的所有网页都是营销号页面的样子

### ISSUE THREAD

**Issue by kingc2022** [liyupi/rubbish-yingxiaohao#9]
![pic1](https://fastly.jsdelivr.net/gh/kingc2022/pic/issue_rubbish-yingxiaohao1.png)
![pic2](https://fastly.jsdelivr.net/gh/kingc2022/pic/issue_rubbish-yingxiaohao2.png)
![pic3](https://fastly.jsdelivr.net/gh/kingc2022/pic/issue_rubbish-yingxiaohao3.png)

**Comment by kingc2022** [comment]
## 不知道咋改, 所以就没提交PR

**Comment by liyupi** [comment]
看能否监听到网页 url 或者内容的变化，重新触发识别
